# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release

on: workflow_dispatch


jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    strategy:
      matrix:
        include:
          - arch: x64
            os: windows-latest
            name: windows
            extension: .exe
          - arch: x86
            os: windows-latest
            name: windows
            extension: .exe

    steps:
    - uses: actions/checkout@v3
    - name: 安装 Python 3.8.10（支持win7的最后一个版本）
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.10"
        architecture: ${{ matrix.arch }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Make package (windows)
      run: |
        pyinstaller -w -F LANDrop/main.py -i LANDrop/icons/app.ico -n LANDrop --hidden-import _cffi_backend
      if: matrix.os == 'windows-latest'
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: LANDrop_${{ matrix.name }}
        path: dist/LANDrop${{ matrix.extension }}
    - name: Get version from tag
      id: extract_version
      run: |
        echo ::set-output name=version::${GITHUB_REF_NAME#v}
      shell: bash
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/LANDrop${{ matrix.extension }}
        tag: ${{ github.ref_name }}
        asset_name: LANDrop-${{ steps.extract_version.outputs.version }}-${{ matrix.name }}-${{ matrix.arch }}${{ matrix.extension }}
        body: |
          PyLANDrop ${{ github.ref_name }}
          
          You can get it from [PyPI](https://pypi.org/project/LANDrop/)
          
  
